### Get all blogs
GET http://localhost:3001/api/blogs

### Add a new blog
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author": "Robert C. Martin",
  "url": "https://blog.cleancoder.com/",
  "title": "Clean Code",
  "likes": 10
}

### Update blog likes
PUT http://localhost:3001/api/blogs/1
Content-Type: application/json

{
  "likes": 3
}

### Delete a blog
DELETE http://localhost:3001/api/blogs/3

### Create invalid blog
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author": "Test Author",
  "url": "https://example.com"
}

### Update blog likes with invalid value
PUT http://localhost:3001/api/blogs/1
Content-Type: application/json

{
  "likes": "cat"
}