### Get all blogs
GET http://localhost:3001/api/blogs

### Create a blog as logged user
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNhdEBleGFtcGxlLmNvbSIsImlkIjoxLCJpYXQiOjE3ODM4MDYxOTd9.rWKz4diKW8WE2TLLE-zPsVVvcGifLzPQ6O99Y6zfg8Y

{
  "author": "Cat Author",
  "url": "https://example.com/cat-blog",
  "title": "Relational databases for cats",
  "likes": 7
}

### Create a blog without a token
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author": "Robert C. Martin",
  "url": "https://blog.cleancoder.com/",
  "title": "Clean Code",
  "likes": 10
}

### Update blog likes
PUT http://localhost:3001/api/blogs/1
Content-Type: application/json

{
  "likes": 3
}

### Delete a blog
DELETE http://localhost:3001/api/blogs/3

### Create invalid blog
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author": "Test Author",
  "url": "https://example.com"
}

### Update blog likes with invalid value
PUT http://localhost:3001/api/blogs/1
Content-Type: application/json

{
  "likes": "cat"
}

### Delete own blog
DELETE http://localhost:3001/api/blogs/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNhdEBleGFtcGxlLmNvbSIsImlkIjoxLCJpYXQiOjE3ODM4MDYxOTd9.rWKz4diKW8WE2TLLE-zPsVVvcGifLzPQ6O99Y6zfg8Y

### Delete another user's blog
DELETE http://localhost:3001/api/blogs/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRvZ3NAZXhhbXBsZS5jb20iLCJpZCI6MiwiaWF0IjoxNzgzODA4MTMyfQ.E3CnpnBcV8B_AuREHHB181mhXaKolmjYylKLMUbaZDM
