### Get all users
GET http://localhost:3001/api/users

### Create an invalid user
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "cat",
  "name": "Senor Cat",
  "password": "secretcat"
}

### Create valid user
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "cat@example.com",
  "name": "Professor Cat II",
  "password": "secretcat"
}

### Create another valid user
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "dogs@example.com",
  "name": "Professor Dog I",
  "password": "secretcat"
}

### Update a user's name
PUT http://localhost:3001/api/users/cat@example.com
Content-Type: application/json

{
  "name": "Professor Cat III"
}

